services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: greymatter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
